version: "3.8"

services:
  postgres:
    container_name: gestao_vagas_postgres
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gestao_vagas
    ports:
      - 5432:5432
